### ISSUE TITLE
希望能加入保存路径的功能和选择画质或提高画质

### ISSUE THREAD

**Issue by MoonChild-LDAL** [AutumnSun1996/ImageTrim#2]
最近刚找到这个软件，很好用，所以很常用，但每次使用都要选择位置真的很烦人，希望可以保存位置，如果因为生成设置文件影响单文件或许可以输入目录默认选在软件所在文件夹，或支持文件拖入只选择输出目录也能少一步。
  还有转换出来的有些图片体积少一半肉眼可见降质，现在硬盘都很大了，希望可以选择保存画质，或者调低PNG压缩率调高JPG质量，谢谢

**Comment by AutumnSun1996** [comment]
关于记录上次保存位置，会需要有个地方存储，目前是考虑在exe所在目录下保存一个配置文件。我后面抽空看看。
图片质量问题可以另外开一个Issue讨论。当前版本下，可以使用PNG格式，它是无损压缩的，应该不会出现质量降低。

**Comment by MoonChild-LDAL** [comment]
好的，我还担心作者不管了呢

**Comment by AutumnSun1996** [comment]
已新增配置保存&加载功能: [Releases v0.1.3](https://github.com/AutumnSun1996/ImageTrim/releases/tag/v0.1.3)
