### ISSUE TITLE
提高图片转换画质

### ISSUE THREAD

**Issue by MoonChild-LDAL** [AutumnSun1996/ImageTrim#3]
希望要么增加输出质量选项，要么调高输出质量，本人肉眼可见降质。
经测试1920×1080的PNG裁剪为1920×1040，体积从3.58M变为2.08M，JPG从1.12M变为556K。

**Comment by AutumnSun1996** [comment]
图像文件的大小和图像质量并不是完全成比例的。裁剪之后的图像像素变少，文件大小降低是正常的。
像你描述的这种大幅降低情况更可能是原始文件压缩率过低导致的。

PNG是无损压缩，每个像素和原图都是一样的，不存在质量降低的问题。
JPG输出的质量是95(最高100)，应该能满足正常使用场景了。
还是不行的话可以先转换为PNG(这个工具的话可以直接改后缀名)，再使用裁剪工具。
